### ISSUE TITLE
Pre-trained models?

### ISSUE THREAD

**Issue by htalibart** [drigoni/RGCVAE#2]
Hi!
Your method seems really interesting, I'm glad to (finally) see a paper where the reconstruction is assessed and good!

When are you planning on releasing pre-trained models?

Thank you!

**Comment by drigoni** [comment]
Hi, 

thank you. I should have them somewhere online, let me find them.

Davide

**Comment by drigoni** [comment]
Unfortunately, I am not able to recover the exact checkpoint. Send me your email address and I will send you a new checkpoint.

**Comment by drigoni** [comment]
Hi, I recovered some old checkpoints, which you can download from here: https://www.dropbox.com/scl/fi/urq9pnl3e190168q2qhku/RGCVAE-checkpoints.tar.gz?rlkey=inb8qwyrs8j3yfr0wa5nrnobp&dl=0
